version: '3'


# context: path to Dockerfile
# env_file: path to .env file
# expose: which port to listen to for communications between the same Docker network
# port: which port to listen to for communcations from outside the Docker network
# depends_on: tells docker in which order to start each container.
#           important to note that it does not govern then relationship between
#           Dockers, ie. if one needs to be restart, Docker will not automatically
#           restart it's dependencies.
services:
      mariadb:
        container_name: mariadb
        networks:
          - inception
        build:
          context: requirements/mariadb
        env_file: .env
        volumes:
          - mariadb:/var/lib/mysql
        restart: on-failure
        expose:
          - "3306"
      nginx:
        container_name: ngnix
        networks:
          - inception
        depends_on:
          - wordpress
        build:
          context: requirements/ngnix
        env_file: .env
        ports:
          - 443:443
      wordpress:
        container_name: wordpress
        env_file: .env
        volumes:
          - wordpress:/var/www/wordpress
        networks:
          - inception
        build:
          context: requirements/wordpress
        depends_on:
          - mariadb
        restart: on-failure
        expose:
          - "9000"

#   network is a virtual software defined network that connects Docker containers.
#   driver: what type of connection
#   bridge driver: the default network driver, creates a private internal network on the host machine
#                and assigns IP addresses to containers on that network. The containers can then
#                communicate using these IP adresses.
networks:
        inception:
            name: inception
            driver: bridge



#   Volumes are data storage that will persist even if the container that is associated with it
#   is interrupeted or deleted.

#   driver: specifies the type of volume, in this case local
#   driver options: 
#   type: not a special type, defaults to "bind" type
#   o: specifies the bind option, in this case a bind mount.
#   device: specifies the path on the host machine where the volume will be mounted into the container


#    <!> VOLUMES WILL HAVE A DIFFERENT PATH WHEN RUNNING TESTS VS RUNNING IN THE VM ITSELF <!>
#       that happens because on the macs we dont have sudo powers to change anything
#       in the home directory.
volumes:
        wordpress:
            driver: local
            driver_opts:
              type: "none"
              o: 'bind'
              # device: /Users/gmiyakaw/Documents/Common_Core_Projects/inception/srcs/temp_volumes/wordpress
              device: '/home/gmiyakaw/data/wordpress'   #NEEDS TO BE CHANGED WHEN RUNNING ON VM VS MACS
        mariadb:
            driver: local
            driver_opts:
              type: 'none'
              o: 'bind'
              # device: /Users/gmiyakaw/Documents/Common_Core_Projects/inception/srcs/temp_volumes/mariadb
              device: '/home/gmiyakaw/data/mariadb'    #NEEDS TO BE CHANGED WHEN RUNNING ON VM VS MACS
